-- ==UserScript==
-- @name         acompressor
-- @version      0.1.0
-- @description  This script adds control to the dynamic range compression ffmpeg filter including key bindings for adjusting parameters.
-- @author       mpv-player
-- @downloadURL  https://raw.githubusercontent.com/mpv-player/mpv/master/TOOLS/lua/acompressor.lua
-- @updateURL    https://github.com/mpv-easy/mpsm-scripts/releases/latest/download/acompressor.meta.lua
-- ==/UserScript==
