name: Releases

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: "build ts"
        run: |
          pnpm i
          pnpm run build

          mkdir -p ./release
          cp ./scripts/* ./release/
          cp ./es5/* ./release/
          cp ./script-opts/* ./release/
          cp ./lua/* ./release/


      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./release/*"
